changelog:
  categories:
    - title: What's changed
      labels:
        - "*"
      exclude:
        labels:
          - dependencies
          - maintenance
    - title: Updated dependencies
      labels:
        - dependencies
    - title: Maintenance changes
      labels:
        - maintenance
