changelog:
  categories:
    - title: Updated dependencies
      labels:
        - dependencies
    - title: Maintenance changes
      labels:
        - maintenance
    - title: What's Changed
      labels:
        - "*"
