name: "backport-action"
description: "Automatically backport pull requests"
author: "zeebe-io"
inputs:
  github_token:
    description: Token for the GitHub API
    required: true
  github_workspace:
    description: The GitHub workspace directory path
    required: true
  label_pattern:
    description: A regex pattern to match the backport labels
    required: false
    default: ^backport ([^ ]+)$
  pull_description:
    description: >
      Template used as description in the pull requests created by this action.
      Placeholders can be used to define variable values.
      These are indicated by a dollar sign and curly braces (`${placeholder}`).
      Please refer to this action's README for all available placeholders.
    required: false
    default: |-
      # Description
      Backport of #${pull_number} to `${target_branch}`.
  pull_title:
    description: >
      Template used as the title in the pull requests created by this action.
      Placeholders can be used to define variable values.
      These are indicated by a dollar sign and curly braces (`${placeholder}`).
      Please refer to this action's README for all available placeholders.
    required: false
    default: >-
      [Backport ${target_branch}] ${pull_title}
runs:
  using: "node16"
  main: "dist/index.js"
