name: "backport-action"
description: "Automatically backport pull requests"
author: "zeebe-io"
inputs:
  github_token:
    description: >
      Token to authenticate requests to GitHub.
      Either GITHUB_TOKEN or a repo-scoped Personal Access Token (PAT).
    default: ${{ github.token }}
  github_workspace:
    description: Working directory for the backport action.
    default: ${{ github.workspace }}
  label_pattern:
    description: A regex pattern to match the backport labels.
    default: ^backport ([^ ]+)$
  pull_description:
    description: >
      Template used as description in the pull requests created by this action.
      Placeholders can be used to define variable values.
      These are indicated by a dollar sign and curly braces (`${placeholder}`).
      Please refer to this action's README for all available placeholders.
    default: |-
      # Description
      Backport of #${pull_number} to `${target_branch}`.
  pull_title:
    description: >
      Template used as the title in the pull requests created by this action.
      Placeholders can be used to define variable values.
      These are indicated by a dollar sign and curly braces (`${placeholder}`).
      Please refer to this action's README for all available placeholders.
    default: >-
      [Backport ${target_branch}] ${pull_title}

  # DEPRECATED
  version:
    description: The version of backport-action - deprecated
    required: false
runs:
  using: "node16"
  main: "dist/index.js"
